services:
  api:
    build: .
    command: poetry run uvicorn fast_zero_async.app:app --host 0.0.0.0 --port 8000 --reload


    ports:
      - "8000:8000"
    env_file:
      - .env
    #volumes:
    #  - .:/app
    #depends_on:
    #  - db_prod

  test:
    build: .
    command: poetry run pytest
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    depends_on:
      - db_tests

  #db_prod:
  #  image: postgres:15
   # container_name: db_prod
    #ports:
     # - "5432:5432"
    #volumes:
     # - postgres_prod_data:/var/lib/postgresql/data
    #environment:
      #POSTGRES_DB: ${POSTGRES_PROD_DB}
      #POSTGRES_USER: ${POSTGRES_USER}
      #POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  db_tests:
    image: postgres:15
    container_name: db_tests
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_TEST_DB}
      POSTGRES_USER: ${POSTGRES_USER_TEST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_TEST}

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    depends_on:
      #- db_prod
      - db_tests

volumes:
  postgres_prod_data:
  postgres_test_data:
  pgadmin_data:
